### ISSUE TITLE
Wrong model geometry in ifc, xkt model

### ISSUE THREAD

**Issue by g-rodigy** [xeokit/xeokit-sdk#1079]
**Describe the bug**
This is part of ifc model, but viewer render not correct. Xkt model also converted from this model.

**Screenshots**
Original:
![image](https://github.com/xeokit/xeokit-sdk/assets/30372087/db8e65c1-7d30-44b4-9b3e-8eaed6a5d400)

Viewer:
![image](https://github.com/xeokit/xeokit-sdk/assets/30372087/6203ceda-e600-4047-92a2-de3e31a0c406)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 114

I don't understand it a viewer bug or wasm parser.
My debug brought me here, but then I can't check the data is valid here.
https://github.com/xeokit/xeokit-sdk/blob/02576b0be6dec9c4d8fc0f45bd408d4ffc05e449/src/plugins/XKTLoaderPlugin/parsers/ParserV10.js#L402-L409

What else can I provide to find the problem?

**Additional context**
xeokit-sdk version 2.3.9

**Comment by xeolabs** [comment]
This bug is likely to be a geometry processing bug within the 3rd-party````web-ifc```` library, which is used within `WebIFCLoaderPlugin` to convert IFC. Unfortunately there's not much we can do on our end, since we just wrap that library. 

In the meantime, I'd suggest using our other conversion tools, which may give better results - see here: https://xeokit.github.io/xeokit-model-conversion-tests/index.html

**Comment by g-rodigy** [comment]
Bug was in ifc model

**Comment by g-rodigy** [comment]
Bug was in ifc model
