### ISSUE TITLE
Xeokit have any community forum?

### ISSUE THREAD

**Issue by brunokunace** [xeokit/xeokit-sdk#1089]
Hi guys, i see many issues about technical doubts here, xeokit have any discord, forum, telegram, slack channel to members discuss about implementations or any other things?

Thanks

**Comment by xeolabs** [comment]
Hi, we use a private Asana instance for supporting requests from our commercial users, whose requirements are driving the xeokit roadmap. If this works for you, then please get in contact here: https://creoox.com/en/3d-viewer/

Otherwise, we're using this issue tracker for community discussion etc. If you have any issues, just go ahead and raise them here for the time being.

Cheers
