### ISSUE TITLE
Fix SectionPlaneControl mouse interaction

### ISSUE THREAD

**Issue by Amoki** [xeokit/xeokit-sdk#1139]
**Describe the bug**
The FaceAlignedSectionPlane plugin is bugged on the example: https://xeokit.github.io/xeokit-sdk/examples/slicing/#FaceAlignedSectionPlanesPlugin

The arrow is not clickable and is hidden by objects behind it.

**Desktop (please complete the following information):**
Tried on Firefox and Chrome on Linux

**Comment by xeolabs** [comment]
Logarithmic depth buffer has the unavoidable side-effect of making nearby objects not align perfectly, which caused section planes to be misaligned. I had it enabled log depth so that vertex/edge snapping would work correctly for distant objects, but it turns out that it can be used internally only for the snapping shaders, and does not need to be enabled for everything else. Therefore, I was able to disable log depth buf by default.

**Comment by Amoki** [comment]
It is still tough to click on the arrows to move them. Clicking on it doesn't always work, clicking a few pixels away sometimes does :/

**Comment by xeolabs** [comment]
Actually I'd never intended for those arrows to be clickable, since the dragging often doesn't map well to 3D movements.  I'd forgotten they were clickable.

This UX experiment really implies that the draggable div is activated for a single section plane at a time, after the section plane is selected from a menu. Then, the section plane is only controllable via dragging that DIV, and it would not be possible to interact with the 3D arrows. 

To complete that example, I'll make the arrows non-clickable soon.

**Comment by Amoki** [comment]
Oh, I was talking about https://xeokit.github.io/xeokit-sdk/examples/slicing/#SectionPlanesPlugin_Duplex, for which clicks seem important.
