### ISSUE TITLE
pick with pickSurface: true fails with xktv10 without normals

### ISSUE THREAD

**Issue by Amoki** [xeokit/xeokit-sdk#1141]
When picking on **instanced** objects with `pickSurface=true` on xktv10 without normals, `pickResult.worldNormal`  equals `[NaN, NaN, NaN]` on Linux and `[-0.57, -0.57, -0.57]` on macOS (whatever the object or position)

```javacript
const pickResult = xeokit.scene.pick({
  canvasPos: coords,
  pickSurface: true,
});
console.log(pickResult.worldNormal)  // [NaN, NaN, NaN]
```

When forcing normals during xkt conversion, it works.

Is it indented behavior?

**Comment by xeolabs** [comment]
It is intended behaviour, yes. Although it probably needs to be documented better. We like to drop normals from the pipeline and geometry representation when we can, because that simplifies things and drops the memory footprint. We have some shaders that generate normals using standard derivatives in the shaders, which could generate normals for pick results, but those are not tested lately, so I'll consider this a breakage for now until we've got those verified.

**Comment by Amoki** [comment]
I investigated a bit more: When normals are in the xkt, it works with VBO rendering but there is still a bug with DataTextures
