### ISSUE TITLE
SectionPlanesPlugin make the model disapper

### ISSUE THREAD

**Issue by ctrlmaniac** [xeokit/xeokit-sdk#1183]
**Describe the bug**
SectionPlanesPlugin does not work on my XKT model. The 3D model disapper when I activate the section planes plugin

**code**
```
React.useEffect(() => {
    // Sections
    if (!isEmpty(viewer)) {
      const sectionPlanes = new SectionPlanesPlugin(viewer!, {
        overviewCanvasId: "myOverviewCanvas",
        overviewVisible: true,
      });

      sectionPlanes.createSectionPlane({
        id: "mySectionPlane",
        pos: [1.04, 1.95, 9.74],
        dir: [1.0, 0.0, 0.0],
      });

      sectionPlanes.createSectionPlane({
        id: "mySectionPlane2",
        pos: [2.3, 4.46, 14.93],
        dir: [0.0, -0.09, -0.79],
      });

      const mySectionPlane2 = sectionPlanes.sectionPlanes["mySectionPlane2"];
      mySectionPlane2.active = showSection;

      mySectionPlane2.pos = [11.0, 6.0, -12];
      mySectionPlane2.dir = [0.4, 0.0, 0.5];

      if (showSection) {
        sectionPlanes.showControl("mySectionPlane2");
      } else {
        sectionPlanes.hideControl();
        sectionPlanes.destroySectionPlane("mySectionPlane");
        sectionPlanes.destroySectionPlane("mySectionPlane2");
      }
    }
  }, [viewer, showSection]);
```

**Expected behavior**

**Screenshots**
![Screenshot 2023-10-18 083746](https://github.com/xeokit/xeokit-sdk/assets/6809907/a123dc2e-ff78-4878-a52b-4b51ebe75d26)
![Screenshot 2023-10-18 083815](https://github.com/xeokit/xeokit-sdk/assets/6809907/15d01751-dcfd-4533-ac88-164bbbebebba)

**Desktop:**
 - OS: windows
 - Browser chrome

**Comment by xeolabs** [comment]
I can't be sure without trying this code with the particular model, but two possibilities:

* Section planes are pointing in a direction that clips the entire model away
* Or issue #1180, which is now fixed in xeokit-sdk 2.4.0-alpha-95

Something to try - try modifying this example by replacing the model with your one, then try creating section planes with the mouse: https://xeokit.github.io/xeokit-sdk/examples/slicing/#SectionPlanesPlugin_createWithMouse
