### ISSUE TITLE
OPTIMIZATION: Make section planes faster to create and remove 

### ISSUE THREAD

**Issue by Amoki** [xeokit/xeokit-sdk#1215]
**Describe the bug**
When dtx is enabled, creating a section plane takes ~3 seconds and 3 seconds to remove.

Tested on Linux, Firefox, and AMD gpu

**To Reproduce**
1. Use https://xeokit.github.io/xeokit-sdk/examples/slicing/#SectionPlanesPlugin_createWithMouse example
2. Add `dtxEnabled: true` to the viewer config
3. Click to create a section plane
4. wait

**Comment by xeolabs** [comment]
That will be because shaders have the section plane clipping logic baked into the glsl, therefore need to be recompiled each time we add a new section plane, to add logic for each new section plane. See profile below - we do `_compile` and `_eagerCreateRenderers`, which recompose and compile the shaders each time we add a plane.
 
![750553f6-2084-402d-bfdf-2647b9ede918](https://github.com/xeokit/xeokit-sdk/assets/83100/697bf868-5c90-4e3f-b734-a0b82b8ddf29)

Solution would be to pre-bake several section planes into the shaders, then enable them as we create new section planes. Then recompile with more pre-baked section planes logic if we need more than that. The penalty would be conditionals within the fragment shader, to skip unused section plane logic. Perhaps that's not a big deal.

**Comment by Amoki** [comment]
I don't think users create often more than 4 section planes.  Pre-bake sections 5 by 5 and having a lag when we try to create the 6th seems very OK :)

**Comment by xeolabs** [comment]
@amoki I just added the option to pre-cache Viewer resources for a specified number of SectionPlanes.

See usage details in the PR: https://github.com/xeokit/xeokit-sdk/pull/1273

Now published in @xeokit/xeokit-sdk 2.4.2-beta-23
