### ISSUE TITLE
Floor of my xkt file isnt displayed correctly

### ISSUE THREAD

**Issue by Layak-Ali** [xeokit/xeokit-sdk#1409]
![Screenshot (46)](https://private-user-images.githubusercontent.com/93964740/310002211-f25deb30-a400-451f-8d39-8ef799400064.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNjQ2ODMsIm5iZiI6MTcxMDI2NDM4MywicGF0aCI6Ii85Mzk2NDc0MC8zMTAwMDIyMTEtZjI1ZGViMzAtYTQwMC00NTFmLThkMzktOGVmNzk5NDAwMDY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDE3MjYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjM2UwOWFlZWYwNmZmMTQ4ZDU5YTc3MTZjZWNlYjcxM2VmMTQ3NTUxMzVmYzBhZmRkNGVkMGU0MThiMjc4YTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hxxBuUjZruNQfg-XFjjfmf97chWv1POUYFOePJk2Kc0)

 The floor of my file isnt displayed correctly. It works fine in gltf and ifc format in other viewers but not in xkt format. Is there any error in my code?

https://github.com/xeokit/xeokit-sdk/issues/1398#issuecomment-1978379012

Unfortunately i cant give send you the ifc file. 
- i tested the ifc file in ifc.js/thatopen.
- convert2xkt, xeokit-metadata and ifcconvert (latest)
- latest

**Comment by xeolabs** [comment]
Try loading the glTF file into xeokit using the GLTFLoaderPlugin. 

If the model still looks incorrect, then that means that the error lies with the IfcConvert tool, so you'll need to log an issue with that project.

If the glTF looks good, then the error is on our side. If that's the case, however, we would then need the glTF file to debug, and probably the IFC as well.

I can't comment on your code though, since you've not shared any in your issue - I don't think that will be the problem though.

**Comment by Layak-Ali** [comment]
it took a long time but it loaded the gltf file well and there was no error in gltf. I think the error lies in the ifcConvert tool. i will check that out
