### ISSUE TITLE
[FEATURE SUGGESTION] Clipping based on a geometry instead of planes

### ISSUE THREAD

**Issue by hamza-hajji** [xeokit/xeokit-sdk#1421]
**Is your feature request related to a problem? Please describe.**
A way to cut a shape into an entity like [SectionPlanes](https://xeokit.github.io/xeokit-sdk/docs/class/src/plugins/SectionPlanesPlugin/SectionPlanesPlugin.js~SectionPlanesPlugin.html) but with any geometry we define, for example with https://xeokit.github.io/xeokit-sdk/docs/function/index.html#static-function-buildBoxGeometry

**Describe the solution you'd like**
A plugin that allows clipping like SectionPlanes but with a geometry like this:

![image](https://github.com/xeokit/xeokit-sdk/assets/26790341/35f0210b-4640-4d6b-acb5-d06b585fe021)

```js
new ClippingPlugin(scene, {
  active: true,
  geometry: buildBoxGeometry(...),
});
```

Or using a technique like [CSG](https://github.com/evanw/csg.js), we could use it like this

![image](https://github.com/xeokit/xeokit-sdk/assets/26790341/c3fbaa84-14ef-4c65-a657-c2f03ede8c14)

```js
XeokitCSG.subtract(modelA, modelB)
```

**Describe alternatives you've considered**

There are some libraries like [threejs-csg](https://github.com/looeee/threejs-csg) that allow to subtract/join a model from another. But it only works with threejs

**Comment by xeolabs** [comment]
No, we don't have any clipping techniques like this currently. 

We do our clipping in the WebGL shaders, in order to do it it in real time while rendering. 

Only clipping against a single plane is efficient to do interactively in a WebGL shader, and a mesh-mesh CSG clipping operation would not be efficient, and would be hard to implement in a shader.

The best option would be to use [csg.js](https://evanw.github.io/csg.js/) with xeokit, to modify the geometry meshes, in JavaScript.
