### ISSUE TITLE
GLTF loader and meta objects structure

### ISSUE THREAD

**Issue by DhivinX** [xeokit/xeokit-sdk#1588]
Hi @xeolabs,

 using the xeokit GLTF loader, can it automatically create a meta object structure? 

As is done when converting with xeokit-convert to an XKT file. 
What I mean is that the structure should be based on existing "entities" in the GLTF model.

**Comment by xeolabs** [comment]
Hi @DhivinX 

At the moment, no. But if we need it, I can add it

**Comment by DhivinX** [comment]
@xeolabs Yes, please. If it's not too much effort.

**Comment by DhivinX** [comment]
Any news on this topic? Of course, I don't want to rush you.

**Comment by xeolabs** [comment]
@DhivinX I have a solution of sorts which I haven't merged yet - let's discuss in the next tech meeting.

**Comment by xeolabs** [comment]
Hi @DhivinX making a metamodel that reflects the node hierarchy turned out to be tricky alongside the other use cases etc - however what I did do is make it produce a two-level hierarchy, maybe that's OK for now - see this PR: https://github.com/xeokit/xeokit-sdk/pull/1599

I'll need to circle back to this later and think through a better parsing solution for the full node hierarchy.

**Comment by DhivinX** [comment]
Hi @xeolabs thank you for quick response. For me it's looks nice and I think that it's enough. Thank you again!
