### ISSUE TITLE
WebGL errors when destroying model and section planes

### ISSUE THREAD

**Issue by tothatt81** [xeokit/xeokit-sdk#174]
Hey there @xeolabs,

Myself and @barnabasmolnar have come across a rather strange bug that I'd like to bring to your attention. Please have a look at the code in the following gist: https://gist.github.com/tothatt81/8a4bf1d5709a80368c4d346fa59a060e

This is what happens:
- a model is loaded with the xktloader plugin
- the section planes plugin is applied, followed by a section plane
- the section planes control is enabled

Now, if after some time I,
1. delete the model
2. hide the section plane control
3. load a new model into the scene

that works fine.

If, however, I destroy the section plane and/or the whole section plane plugin itself before adding the new model, I get the following webgl errors:

`WebGL: INVALID_OPERATION: drawElements: no buffer is bound to enabled attribute`
`WebGL: INVALID_OPERATION: drawElementsInstancedANGLE: no buffer is bound to enabled attribute`
(the latter one when I destroy the whole plugin)

Any idea why this might happen? We're pretty much at a loss here. Personally I've made quite a few attempts to debug the issue but in the end I always end up facing the sequence described above.

**Comment by xeolabs** [comment]
Eeek. Making this a priority for this week.

**Comment by xeolabs** [comment]
I fixed it by disabling all WebGL vertex attribute arrays after each render: https://github.com/xeokit/xeokit-sdk/commit/62d90f86479bd9904a1d6aad5fd1f0b7f130572f#diff-5e667dbdc4e07412e0405808ddc27a70R608

I accidentally committed part of another unrelated feature with that file, but it doesn't affect anything.

It seems wasteful to disable a whole bunch of vertex attribute arrays after each render, so will investigate if unbinding the currently active WebGL program is more efficient, which implicitly unbinds everything, but for now we can go with this fix.

Usually with WebGL we don't bother unbinding things, but it turns out that xeokit needs this because it uses lots of different shaders, which can change dynamically and lead to these inconsistent WebGL states.

**Comment by barnabasmolnar** [comment]
I just tested it, looks good for my particular use case. Thanks Lindsay!

@tothatt81, would you please conduct your own tests as well?

**Comment by tothatt81** [comment]
It looks good to me as well, thanks.
