### ISSUE TITLE
BCF camera position is wrong in ortho projection.

### ISSUE THREAD

**Issue by Amoki** [xeokit/xeokit-sdk#245]
```js
viewer.camera.projection = "ortho"

const viewpoint = bcfViewpointsPlugin.getViewpoint();
bcfViewpointsPlugin.setViewpoint(viewpoint);
```
And the camera is not in the same position

**Comment by xeolabs** [comment]
Fixed in https://github.com/xeokit/xeokit-sdk/commit/5bf6c15a192b2a24e731d28b74726557d90223fc

Tests:

* save viewpoint for ortho camera: 
https://xeokit.github.io/xeokit-sdk/examples/BCF_SaveViewpoint_ortho.html

* load same viewpoint, for ortho camera:
https://xeokit.github.io/xeokit-sdk/examples/BCF_LoadViewpoint_ortho.html

**Comment by Amoki** [comment]
Thanks!
