### ISSUE TITLE
GUID clashes

### ISSUE THREAD

**Issue by barnabasmolnar** [xeokit/xeokit-sdk#275]
Hey Lindsay,

Barna here from bimspot. We have an interesting use case that I'd like to ask you about.

As you probably know, we want to show multiple models in the same viewer (federated models). This has worked quite well for us thus far but we've been wondering about the following potential scenario:

Say we have ARC and MEP models where some walls have the same GUIDs. Now I'm well aware that even the name indicates that these IDs should be unique globally but in our case we can't exactly guarantee that. What we want to do is show/hide, xray or colorize elements on a GUID level. The API you have for this is really clean and works very well when the IDs are in fact unique.

@tothatt81 did some tests, however, with duplicated GUIDs and it seems that in this case only those elements get registered that belong to the model that was loaded into the viewer last. Our preference would be to be able to show/hide, xray, colorize say Wall X in both the ARC and MEP models.

Would you be able to look into that please, give us some pointers perhaps?

Cheers!

**Comment by xeolabs** [comment]
This one falls into the realms of paid consultancy I'm afraid. I'd like to help, but the issue is that it's incredibly easy to end up working on a zillion solutions for various startups without being on anyone's payroll!

**Comment by barnabasmolnar** [comment]
Duly noted! I'm sure we'll be in touch.

**Comment by eriadam** [comment]
Hi Lindsay,

We discussed this today and came to the conclusion that this is not something the viewer should be solving. GUIDs should be, as their name implies, unique. We need to make sure only distinct ids end up in the mesh. Otherwise the UX is inconsistent.

What I could think of is a kind of warning or filter, like the one with the complex elements so that xeokit users can inform their product users about such duplicated elements. Then again, this is a nice to have. A note in the documentation should suffice.

Cheers,
Adam
