### ISSUE TITLE
Fix disappearing models after pivot from downward-looking direction

### ISSUE THREAD

**Issue by lasselaakkonen-congrid** [xeokit/xeokit-sdk#289]
When `cameraControl.pivoting = true`, the canvas goes completely blank in some specific scenarios when rotating the view.

The issue can be reproduced with NavCubePlugin or without NavCubePlugin by manually setting the same camera eye/look/up values as the NavCubePlugin sets.

## Reproducing with NavCubePlugin

Using macOS Chrome v80.0 and xeokit-sdk v0.9.93.

Load a model like this:

```
        const viewer = new Viewer({
            canvasId: "3DViewerContainer",
            transparent: true,
        });

        const model = xktLoader.load({
            src: "samplehouse.xkt",
        });            

        const cameraControl = viewer.cameraControl;
        cameraControl.pivoting = true;

        const navCube = new NavCubePlugin(viewer, {
            canvasId: "NavigationCubeContainer",
        });
```

Change to the Top view from the NavCube.

Try to rotate the model by clicking and dragging.

The canvas goes blank without anything in console logs.

![xeokit-crash-navcube-pivoting-1](https://user-images.githubusercontent.com/25615985/79834405-b0fe5a80-83b5-11ea-80a2-6ecbdbe73a48.gif)

**Comment by xeolabs** [comment]
For future debugging reference: issue is due to the angle between camera ````worldUp```` and ````eye````->````look```` being zero at the start of the pivot, causing elements of the ````lookat```` matrix to be ````NaN````.

Solution is to make this math more robust for this case, not sure how yet.

![Screenshot from 2020-04-21 11-01-15](https://user-images.githubusercontent.com/83100/79847079-83b6aa00-83bf-11ea-8701-6fd3c1a604f7.png)

**Comment by xeolabs** [comment]
Will fix by using the length of the cross product to test whether the angle between the two vectors is too small, eg in Helix:
https://github.com/DerSchmale/helixjs/blob/master/src/helix-core/math/Matrix4x4.js#L1393

**Comment by xeolabs** [comment]
I just changed title because clicking TOP on the NavCube is a reliable way to reproduce this issue.

**Comment by xeolabs** [comment]
This bug is caused by pivoting math breaking for the case when we start pivoting while initially looking directly downwards.

I wasn't able to make the pivoting math robust for this case, however I was able to implement a UX workaround which is minimally disruptive.

As shown in the screenshot below, if we're not initially looking directly downwards, then we pivot about the position we click.

If however we are initially looking directly downwards, the first click and drag just orbits the camera about it's current point-of-interest. On a subsequent drag, since the camera is 99.99999% likely to no longer be looking directly downwards, we set the pivot point to the mouse position on the object surface, and pivot that as expected.

The UX compromise here is that if the user was planning to do a pivot about a clicked point right after selecting a downward-looking viewpoint (eg. using NavCube), then as they drag they'll notice they're not pivoting as expected, and are then likely to attempt to pick the pivot point again. Better than the model disappearing!

![Animated GIF-downsized_large (32)](https://user-images.githubusercontent.com/83100/98991075-9e06cf80-252b-11eb-8228-8e3dd1c74a5d.gif)
