### ISSUE TITLE
doublePicked, doublePickedNothing gets fired twice on mobile devices

### ISSUE THREAD

**Issue by blickfeld7** [xeokit/xeokit-sdk#366]
on mobile devices the doublePicked events get fired twice while on desktop devices they're working as expected.

**Comment by xeolabs** [comment]
This happens because ````CameraControl```` is binding both mouse and touch event listeners, so on a mobile device, a single tap will fire a both a mouse and a touch event. 

@blickfeld7 any thoughts? 

Perhaps if mobile devices always fire mouse events, then this issue could be fixed by removing the picking touch logic from ````CameraControl````, and relying on the mouse touch logic for both mobile and desktop?
