### ISSUE TITLE
CameraControl "orbit" mode can't dolly through objects with nothing behind them

### ISSUE THREAD

**Issue by eriadam** [xeokit/xeokit-sdk#367]
Cannot go through walls, slabs. (Not an outer element of the model.)
Sometimes the blocking elements disappear, but are still selectable (see screenshots).

<img width="590" alt="Screenshot 2020-06-19 at 10 04 53" src="https://user-images.githubusercontent.com/2480660/85896366-a074c100-b7f8-11ea-80fe-ac2067297667.png">
<img width="565" alt="Screenshot 2020-06-19 at 10 04 56" src="https://user-images.githubusercontent.com/2480660/85896371-a1a5ee00-b7f8-11ea-975b-bf87389d35df.png">

Version 1.3.52

**Comment by xeolabs** [comment]
This seems to occur when ````CameraControl```` ````navMode```` is "orbit", but not when it is "firstPerson". 

The cause of this issue is that ````CameraControl```` dollying works by continually performing a ray-pick along the camera line-of-sight to find the distance to the nearest object, to adjust dolly speed according to that distance. When we dolly completely through a model, arriving at the last element along our dolly path, there are no more objects to ray-pick and so the adjusted dolly speed becomes zero.

Will fix by setting dolly speed to a sensible default in that case.

**Comment by xeolabs** [comment]
I'm not sure what is/was causing this particular issue. 

Can you reproduce this currently with any of the live demos?
