### ISSUE TITLE
Create annotations based on the id of an entity

### ISSUE THREAD

**Issue by ESiham** [xeokit/xeokit-sdk#374]
Hello,
I have an issue, I want to create annotations based on the id of an entity, for example, to create an annotation for a wall I should get the id of this wall and based on this id I should create the annotation, I searched in the Github page but I found that all examples are created with the worldPos, so can someone help me? I would be very grateful.

**Comment by xeolabs** [comment]
Maybe this example is useful: 

https://xeokit.github.io/xeokit-sdk/examples/#annotations_createAtCenterOfClickedObject

In this example, whenever we click on an object, we: 

- get the center of the object's axis-aligned bounding box, then 
- create a new annotation, setting worldPos to that center position.  

Note that when we click an object multiple times, we create a bunch of annotations at the same worldPos. A useful extension to this example would be to somehow automatically offset the annotations from the object center as they are created, perhaps radially, so that they don't overlap.

Note also that we create each annotation with ````occludable: false````. By default, an annotation's marker and label are hidden when the annotation's position is occluded by something in the 3D view. Since our annotations are created at the center of their objects, we need to configure them  ````occludable: false```` to disable that occlusion behavior, otherwise they would be constantly occluded by their objects, which would cause their markers and labels to always be hidden.

**Comment by ESiham** [comment]
thanks @xeolabs for help  this is exactly what I am searching for.
