### ISSUE TITLE
TreeViewPlugin problem to load json

### ISSUE THREAD

**Issue by cfardito** [xeokit/xeokit-sdk#442]
Hello,
I have recently started using xeokit to view industrial assets within a WebApp. It works with the files in the examples folder (xeokit-sdk: attached I put an image of the relative view Viewer_OTCConferenceCenter.PNG) but when I try to view an external ifc file a strange thing happens: the 3D is displayed correctly but the ThreeView does not show (attached the image: Viewer_Beam_ThreeView problem.PNG).
To convert the file from .ifc to .xkt I followed the procedure from the following link (https://github.com/xeokit/xeokit-sdk/wiki/Creating-Files-for-Offline-BIM).
No errors are displayed in the browser console.
I don't understand where I'm wrong.
I attach the .xkt file and the .json file. It is a simple file with a beam. For completeness, I also attach the original .ifc file.
Please help me because I am going crazy for two 3 days!!!

Thank you all

Viewer_Beam_ThreeView problem.PNG
![Viewer_Beam_ThreeView problem](https://user-images.githubusercontent.com/72459057/95226628-75d5d380-07fd-11eb-8efb-e1c7b5def606.PNG)

Viewer_OTCConferenceCenter.PNG
![Viewer_OTCConferenceCenter](https://user-images.githubusercontent.com/72459057/95226632-766e6a00-07fd-11eb-87cf-18a7c3782d19.PNG)

the zip contains: .ifc; .xkt; .json.
[beam-extruded-solid.zip](https://github.com/xeokit/xeokit-sdk/files/5335167/beam-extruded-solid.zip)

**Comment by xeolabs** [comment]
Hi @cfardito, I'm not able to unzip the zip you've attached - could you re-zip that or attach the files separately?
Thanks

**Comment by cfardito** [comment]
Hello,
here are the files. Thank you

[beam-extruded-solid_1.zip](https://github.com/xeokit/xeokit-sdk/files/5339027/beam-extruded-solid_1.zip)

**Comment by cfardito** [comment]
> Hi @cfardito, I'm not able to unzip the zip you've attached - could you re-zip that or attach the files separately?
> Thanks

Hi @xeolabs,  is there any news? thank you

**Comment by xeolabs** [comment]
@cfardito I just put the IFC file through ````xeokit-gltf-to-xkt```` and ````xeokit-metadata````, than dropped the ````.xkt```` and metadata files into the ````TreeView_Containment.html```` example, and I got a tree view appearing correctly, but the beam object's position coordinates appear to be too big to render in WebGL, so the object does not appear for that reason.

The boundary of the object is:
````[0, 0, 0, -7.224914089216815e+29, 0, 1.030397078214113e+36]````

Is there a way to author the IFC so that the object is positioned closer to the origin?

BTW, I also processed the IFC file using the next version of ````xeokit-gltf-to-xkt```` and ````xeokit-sdk````, which together preserve full-precision geometry, and the object appeared nicely.

So the next version of ````xeokit-sdk```` will solve this problem. Aiming to get a beta release of that out next week.

In the meantime, see if you can center the object as a workaround.

Here's my modified example: https://gist.github.com/xeolabs/e6ec64cf7c1ae18cdeb2f33c64b0783a

And this was what it produced:
![Screenshot from 2020-10-09 12-18-55](https://user-images.githubusercontent.com/83100/95572121-cdf11d80-0a29-11eb-8dc4-febdacfb510c.png)

**Comment by imadBelaroussi** [comment]
please, you got a respances?

**Comment by xeolabs** [comment]
To fix this (per my findings mentioned in previous comment), 

1. update to the latest ````xeokit-sdk```` (1.5.14 or later) and the latest ````xeokit-gltf-to-xkt```` (0.0.61 or later)
2. run ````gltf2xkt```` using the ````-v 6```` option to create XKT V6 format

In my experiments, the JSON metadata file was OK, and the tree view appeared OK, but now you need to use xeokit's new full-precision feature to display your object correctly.

BTW I'm limited in how much support I can provide non-commercial users, however if your enterprise requires an SLA, do get in touch.

**Comment by imadBelaroussi** [comment]
thank you
