### ISSUE TITLE
Discussion of initial buffer sizes for BatchingLayer/BatchingLayer classes

### ISSUE THREAD

**Issue by tmarti** [xeokit/xeokit-sdk#45]
In `viewer/scene/PerformanceModel/lib/batching/batchingBuffer.js`, following piece of code can be found:

```
const MAX_VERTS = SLICING ? (bigIndicesSupported ? 5000000 : 65530) : 5000000;
```

That code works flawlessly on desktop browsers.

BUT on Android/iOS devices, having those big initial sizes is something the mobile versions of the JS engines don't seem to like (tested it with Chrome+Firefox on Android and Chrome+Safari on iOS) .

In the best case, it's possible to attach the PC web inspector to the devices and see an error like "you consumed too much memory". In the worst case (Safari/iOS), the browser TAB simply crashes (with a very generic error message).

Of course this does not happen for the case of loading one performance model (via GLTF loader plugin in my case), but as more and more models are loaded, that big initial size combined with things like (on same class):

```
this.indices = bigIndicesSupported ? new Uint32Array(MAX_VERTS * 6) : new Uint16Array(MAX_VERTS * 6); // FIXME
this.edgeIndices = bigIndicesSupported ? new Uint32Array(MAX_VERTS * 6) : new Uint16Array(MAX_VERTS * 6); // FIXME
```

(those two previous lines alone pre-allocate 5M · 6 · sizeof(uint32 or uint16) = 120 or 60 MB)

I've successfully tested with lowering the first line from 5M to 200k (after some trial and error):

```
const MAX_VERTS = SLICING ? (bigIndicesSupported ? 200000 : 65530) : 200000;
```

And then I was able to load four quite complex models at the same time on mobile browsers.

The reason to title "discussion of..." to this issue is because I'm not fully aware of the consequences of this proposed change (nor of the "most proper" intial array sizes).

e.g. I also see that that 5M number is also used on `viewer/scene/PerformanceModel/lib/batching/batchingLayer.js`:

```
const tempUint8Vec4 = new Uint8Array((bigIndicesSupported ? 5000000 : 65530) * 4);
```

So there we go, just wanted to share this finding and have some discussion about if it's a good change.

**Comment by xeolabs** [comment]
Ah yes, I can see how using MAX_VERTS might be asking for trouble in some browsers. I think reducing that is a good idea, even for when we are just loading one model at a time. 

Reducing that buffer size would be a good idea, but in addition to that, what about if I were to make xeokit internally schedule the loading of multiple models, so that it loads them one at a time?  Would that still be usable, or is being able to load them concurrently desirable?

**Comment by xeolabs** [comment]
Serializing the glTF loads means that 

* only one ````BatchingBuffer```` instance would be used by all ````PerformanceModels````, since they can reuse that single instance, and
* AJAX loads never happen concurrently

And yes the rest of loading is in the same thread, so that is serial anyway. 

Internally, ````BatchingLayer````, which batches geometries using ````BatchingBuffer```` as array scratch memory, does roughly one draw call per geometry batch. So, if all the geometry for a ````BatchingLayer```` fits in one ````BatchingBuffer````, then that ````BatchingLayer```` can render itself in one draw call. If it requires two ````BatchingBuffers```` (actually reusing the same ````BatchingBuffer````), then that's two draw calls, and so on.  So bigger array sizes means less draw calls. But we **can** afford to do multiple draw calls per frame, so reducing the size of the arrays is OK. 

Just need to find the balance, where the arrays sizes need to be large enough for performance, but not so large that theyu create memory pressure as you've found. 

What size would you recommend for the ````BatchingBuffer```` arrays? Did 200000 seem to be a good number?
