### ISSUE TITLE
Support for flat shading PerformanceModels

### ISSUE THREAD

**Issue by burgreen** [xeokit/xeokit-sdk#51]
Could you add support for this? 
I manually disabled lambertian in batchingDrawShaderSource.js. That got me close, but washed out the color.
Thanks.

**Comment by xeolabs** [comment]
If I understand this issue correctly, this would require changes to the way xeokit represents geometry, since xeokit uses per-vertex normals, which are reused for adjacent triangles.

This would require xeokit's geometry and renderer to support per-face normals, which would complicate things too much at this stage.

Theoretically, you could duplicate the vertex normals, so that you could make them perpendicular to the adjacent faces, but you would also need to duplicate vertices, so... we'd rather stick with per-vertex ;)
