### ISSUE TITLE
When the model is loading it increase js memory heap

### ISSUE THREAD

**Issue by vadimt2** [xeokit/xeokit-sdk#558]
When i'm trying to load large models it's increases the memory heap.
When i'm uploading one model i can see the memory jumping from 100 mb to 300-400 mb.

if i'm uploading a few models to xltLoader it's taking a huge amount of memory from the heap, 300mb for each model.
but after all the models are loaded the memory heap decrease and going back to normal.

what can i do to improve the memory heap when the model is loading ?

**Comment by xeolabs** [comment]
As XKTLoaderPlugin loads a model, it accumulates the model's geometry in buffer arrays, then once the geometry is loaded, creates WebGL VBOs from those arrays, then deallocates the arrays.

So, that's the heap grow-and-collapse you're seeing. 

Pretty much all WebGL engines build CPU-side JavaScript geometry arrays as they load models, and will usually keep those arrays in JS memory. So for those engines, the heap grows and stays there.

In xeokit's case, in order to fit more geometry into browser memory, we don't keep geometry arrays in JavaScript memory, so once we've allocated the WebGL VBOs, we immediately delete the JS arrays, and so the heap collapses again.

The maximum size that is actually allocated in these arrays is determined by constant ````MAX_VERTS````, which is defined [here](https://github.com/xeokit/xeokit-sdk/blob/0e23dd76c33fcc77db5e4773efc5e52bab4f42c5/src/viewer/scene/PerformanceModel/lib/batching/BatchingBuffer.js#L4).

A lower value for ````MAX_VERTS```` would make the temp buffer heap size smaller, but would also reduce drawing performance for big models, since it would shorten WebGL geometry batches and result in more WebGL draw calls per frame.

It would be interesting to measure loading speed, rendering performance and (somehow) device stability for different values of ````MAX_VERTS````. 

So it's a trade-off - use a big chunk of heap while loading, so you draw more quickly while rendering. But if that causes instability on low-memory devices, it might be worth reducing that value, or somehow automatically calculating it (perhaps by sniffing the browser?)

**Comment by xeolabs** [comment]
A quick test of loading and rendering speed for various values of ````MAX_VERTS````, using the [Lyon example](https://xeokit.github.io/xeokit-sdk/examples/#logDepthBuf_XKT_Lyon), which exclusively uses geometry batching:


| ````MAX_VERTS```` | Loading time   | Draw calls  | Rendering perf. |
| ------------- |:-------------:| -----:| -----:|
| 1000 | 11.05s | 5890 | ~5FPS |
| 5000 | 10.17s | 1272 | ~30FPS |
| 7500 | 9.31s | 880 | ~40FPS |
| 10000 | 9.40s | 682 | ~50FPS |
| 20000 | 9.6s | 374 | ~50FPS |
| 5000000 | 9.4s | 9 | ~60FPS |

**Comment by vadimt2** [comment]
I will look at it, tnx).
How i can load huge model without freezing the ui ?

**Comment by xeolabs** [comment]
We don't the means to concurrently update the UI while loading a model at the moment. Are you working on a commercial project BTW?

**Comment by Amoki** [comment]
JS is single-threaded so nothing can be computed during heavy JS workload.
However, some CSS animations can still be available during this time: https://stackoverflow.com/questions/6805482/css3-transition-animation-on-load

**Comment by vadimt2** [comment]
@xeolabs for now it's for development and testing only.
Right now we are running some tests and checking if we can use xeokit.
if we will make it work as we need before we will use it for commercial proposes we will buy the licensee.
at the moment we don't know if we will use xeokit for our project, right now it seems to be good.

**Comment by xeolabs** [comment]
@vadimt2 cool. BTW, see #559

**Comment by Amoki** [comment]
@xeolabs you're talking about constant memory, not about loading memory.
There may be optimization we can do when geometries are loaded and xkt and js geometries and webgl geometries are in memory at the same time.


```javascript
const xkt = xkt.parse(xktFile);
const geometries = xkt.geometries.map(geom => parseGeom(geom));
const webglGeometriesToSendToGPU = geometries.map(geom => buildWebGlGeometries(geom));
```


```javascript
const xkt = xkt.parse(xktFile);

const arrayLength = xkt.geometries.length;

for (let i = 0; i < arrayLength; i++) {
	const geometry = xkt.geometries.pop();  // Removing the geometry from the array so the CG can collect it before it will collect the array
	const webGLgeometry = buildWebGlGeometries(geometry);
}
```

I don't know if loading works like that, but here is an example of what I say.

In the first script, xkt is fully parsed in memory, then all geometries are computed and stored in memory then all webGL geometries are computed and stored. It means we have many stuff in memory at the same time. Most of them will be released by the garbage collector, but later.

On the second script, geometries are computed one by one and the memory is released at each step.
It may cost a bit more, but the GC is quite slow and can be faster when memory is cleared.
If xkt file stores objects's data successively, we could go further and do the same when parsing the xkt.
