### ISSUE TITLE
Measurement tool blinks

### ISSUE THREAD

**Issue by Amoki** [xeokit/xeokit-sdk#582]
**Describe the bug**
The lines and labels blink depending on the camera.

**To Reproduce**
1. Create a measure
2. zoom a bit
3. move
4. See the lines and labels blink

**Expected behavior**
Measurement tool to be constantly visible

**Screenshots**
![blinking_lines](https://user-images.githubusercontent.com/1349751/110495436-cc20a880-80f4-11eb-8830-57e7660c9ad6.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: tested and Chrome and Firefox
 - Version: latests

**Comment by xeolabs** [comment]
This happens when one of the end points falls in front of the near clipping plane. This causes the ````Marker```` that manages that clipped end point to be flagged as invisible, which then causes the whole measurement to be hidden (intended behaviour).

We'll need to implement a line clipping algorithm to deal with this - needs thought on where to integrate that -  I'll get it in the next minor release.
