### ISSUE TITLE
Fix ray-pick projection matrix near plane

### ISSUE THREAD

**Issue by juho-ylikyla** [xeokit/xeokit-sdk#728]
**Describe the bug**
Picking in the horizontal direction returns inconsistent results.

**To Reproduce**
1. Copy and paste the following code to the examples directory. Run it in chrome or safari. https://gist.github.com/juho-ylikyla/bbe22c47a1bd640e04182538a23b08dd#file-measurements-more-off-from-hit-entity
2. Click around, for example, a door
3. See that sometimes the measurements go through objects

**Expected behavior**
Measurements should be consistent. We should not go through objects. Seems that sometimes the normal direction is flipped.

**Screenshots**

https://user-images.githubusercontent.com/62982612/133752856-3043e7dc-2b92-48cb-bbe0-62817cde634a.mp4

**Desktop (please complete the following information):**
 - OS: ios or macOS
 - Browser Safari or chrome 92.0.4515.159 (Official Build) (x86_64)
 - Version 92.0.4515.159 (Official Build) (x86_64)
 - Xeokit version `2.0.0-beta.24 `

**Additional context**
This seems to happen with `pickSurfacePrecision: true`. My guesstimate is that something goes wrong in [here](https://github.com/xeokit/xeokit-sdk/blob/424f799cb3d19f3dde7fc486736b7cd146da2ca5/src/viewer/scene/PerformanceModel/lib/layers/trianglesInstancing/TrianglesInstancingLayer.js#L959).

**Comment by xeolabs** [comment]
@juho-ylikyla  I found the issue - within the ray-picking logic, we generate view and projection matrices from the ray, which we use in the picking shader. I'm deriving the project matrix near clipping plane from the camera, which is not a good idea because the near plane could be too far, which might be OK for the camera, but not suitable to reuse for picking logic.

https://github.com/xeokit/xeokit-sdk/blob/master/src/viewer/scene/webgl/Renderer.js#L858

I substuted ````0.01```` for the near plane, and my tests seemed to work, ie:

````javascript
 const pickFrustumMatrix = math.frustumMat4(-1, 1, -1, 1, 0.01, scene.camera.project.far, tempMat4a);
````


Just got to make a regression test, and ensure no side effects, then I'll publish a fix.

**Comment by xeolabs** [comment]
@juho-ylikyla I've published a fix in xeokit-sdk 2.0.0-beta.26 - let me know if that fixes this one..

**Comment by juho-ylikyla** [comment]
Thank you for looking into this 🙏 

Unfortunately, things did not improve. Please let me know if the code I provided to reproduce this issue is somehow flawed or the way I am implementing the measurement is fundamentally wrong so we can look into some other ideas on how to make the measurement tool usable on touch devices.

**Comment by xeolabs** [comment]
It seems there are some times when the picking does not work, not sure why. 

https://xeokit.github.io/xeokit-sdk/examples/picking_surface_canvas_precision.html

I will continue to debug, because we need this to work robustly. I'm going to push a 2.0 release because it's otherwise working fine according to tests, then patch any fixes for this after that.

**Comment by Kurtil** [comment]
`pickFrustumMatrix`does no longer exist due to a fix of the ray picking. [This PR](https://github.com/xeokit/xeokit-sdk/pull/1168/files#diff-53400b46a9da8069b1bbf742925b3b702739614125b28d851340c4c7620aa6faR951) may fix this issue.
