### ISSUE TITLE
SectionPlanesPlugin - Win/Edge/Chrome hangs with more than 5 section planes 

### ISSUE THREAD

**Issue by PetersenDB** [xeokit/xeokit-sdk#814]
Hi, 

while working with section plane plugin, my browser (Edge/Chrome) freeze when I try to add a 6. plane.

It also happens in the example: https://xeokit.github.io/xeokit-sdk/examples/#gizmos_SectionPlanesPlugin_createWithMouse

Is it possible to solve this in code?

**Comment by PetersenDB** [comment]
and also the function .clearAll() is not working for more then 4 planes.

**Comment by xeolabs** [comment]
Hi, I don't think there's much we can do in code for this, since there is no hard-coded limit on the number of section planes in the code (on my machine running Chrome/FF on Ubuntu I was able to create 10+ section planes without problems).

I think the Windows WebGL support is choking on the shaders that xeokit creates internally for 6+ section planes. Each section plane is an additional conditional expression in the shaders, and I think Windows/Edge/Chrome is possibly hitting the limits of what it can handle here.
