### ISSUE TITLE
WasmPath not working

### ISSUE THREAD

**Issue by assaad97** [xeokit/xeokit-sdk#878]
hello, im trying to use the new WebIFCLoaderPlugin, to load Ifcs, and it requires a path to a wasm file, which i provide using the default cdn provided in the examples, when i did that it doesn't work, and if i download the wasm file localy, place it in src and provide a relative wasm oath, it doesn't work either
![image](https://user-images.githubusercontent.com/50522164/175315500-b18d9cf0-2d7e-4c80-9ab4-f2fc9c9cf83c.png)

im using xeokit v2.2.2 in react17 , if there anyone who had this problem and solved it i would really appreciate it

**Comment by xeolabs** [comment]
Sounds like a ReactJS issue (which unfortunately we can't help much with, since it's a 3rd-party lib outside the responsibility of xeokit).

On our end, the best we can do is use the best JS practices we can, and hope that frameworks like ReactJS and Vue do as well.

What happens when you use this feature in a basic HTML page, served from something like ````http-server````?

If that works OK, then it would likely be a React configuration issue..
