### ISSUE TITLE
Load from web worker

### ISSUE THREAD

**Issue by g-rodigy** [xeokit/xeokit-sdk#919]
Is there an easy way to load ifc models in web worker like [ifc.js](https://ifcjs.github.io/info/docs/Guide/web-ifc-three/Tutorials/AdvancedLoading#set-up-the-webworker)

**Comment by xeolabs** [comment]
* [WebIFCLoaderPlugin](https://xeokit.github.io/xeokit-sdk/docs/class/src/plugins/WebIFCLoaderPlugin/WebIFCLoaderPlugin.js~WebIFCLoaderPlugin.html)
* [Tutorial](https://www.notion.so/xeokit/Viewing-an-IFC-Model-with-WebIFCLoaderPlugin-9a572b801af949bf87a21c88968bd251)

**Comment by g-rodigy** [comment]
I read the tutorial and documentation, and there I did not find anything about workers in the plugin, only about custom dataSource.

**Comment by g-rodigy** [comment]
Can you get more details or some small example?

**Comment by xeolabs** [comment]
Now I understand what this issue is asking: Does WebIfcLoaderPlugin has a mode in which it can use workers to parse IFC.

While web-ifc does have the option to use workers, we have not yet exposed that configuration via WebIFCLoaderPugin.

We can add that if partners require it, and of course are always welcoming of PRs if anyone's keen.

PS. in order to avoid wasted time and effort in future, we ask that issues in future have meaningful titles and enough information for us to comprehend them. Thanks
