### ISSUE TITLE
Values of numVisibleObjects and visibleObjectsIds are not matching

### ISSUE THREAD

**Issue by rafaeldemiranda95** [xeokit/xeokit-sdk#937]
Hello.

I have a problem with a federated model. I'm trying to make some elements invisible and other elements visible and selected, but values of numVisibleObjects and visibleObjectsIds are not matching:

![image](https://user-images.githubusercontent.com/37124918/193155297-f83ede4d-db78-4736-9de0-bb204050aef4.png)

![image](https://user-images.githubusercontent.com/37124918/192925294-141965b1-5b93-4d6c-8f88-19bd648d449b.png)

Could this issue be resolved with Xeokit or would it be a modeling issue?

Model: https://github.com/rafaeldemiranda95/ifc-problem-rubk

**Comment by xeolabs** [comment]
Hi, this sounds like a xeokit issue, since the Viewer should never allow those counts to mismatch like that - I'll investigate.

Would it be OK with you if I added these models to the [xeokit-model-conversion-tests](https://xeokit.github.io/xeokit-model-conversion-tests/tests.html)? Then we can use them for a sort of regression test.

**Comment by rafaeldemiranda95** [comment]
You can use these models. Thank you.

**Comment by rafaeldemiranda95** [comment]
Yes, you can use these models. Thank you.

**Comment by xeolabs** [comment]
Hi, could you try again with the latest alpha release? 
This may be fixed now, see https://github.com/xeokit/xeokit-sdk/issues/991

**Comment by rafaeldemiranda95** [comment]
Hello, @xeolabs. 

The problem was fixed. Thank you!
