### ISSUE TITLE
Edges geometry issue on Android 7 / Brave browser

### ISSUE THREAD

**Issue by AlABarazi** [xeokit/xeokit-sdk#94]
The examples look as below on mobile device

<img width="468" alt="Screenshot 2019-06-18 at 16 58 10" src="https://user-images.githubusercontent.com/7549404/59690838-bc5b8500-91ea-11e9-8f23-b6db0778c134.png">

![Screenshot 2019-06-18 at 16 57 58](https://user-images.githubusercontent.com/7549404/59690840-bd8cb200-91ea-11e9-8c74-f8795eff432d.png)

Is this a bug? Does xeokit-sdk support mobile devices (tap, zoom, rotate..etc)?

**Comment by xeolabs** [comment]
It looks like a bug, yes. 

xeokit should also support touch input.

What type of mobile device and OS are you using?

Any errors in the JavaScript console?

Also, do any xeogl examples show the same problem: http://xeogl.org/examples/

**Comment by alabrazi** [comment]
I am using Android  7 and Brave browser. Tapping on the element work but zooming in/out  on mobile has a glitch. Instead of zooming the scene in/out it zoom the page in/out or maybe both the page and the scene together but it is not proper interaction.

I tried one example from http://xeogl.org/examples/ and it seems that its working fine. 

In my opinion some of the control widgets are hard to use on small mobile screens with fingers like this one 

<img width="786" alt="Screenshot 2019-06-19 at 10 35 35" src="https://user-images.githubusercontent.com/7549404/59745824-4143ae80-927e-11e9-966d-2287601ecd2c.png">

I think mobile friendly control widgets like using sliders would enhance UX.
